// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("honeycombmarker")
	ScopeName = "github.com/GlancingMind/opentelemetry-collector-contrib/exporter/honeycombmarkerexporter"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
