// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("opencensus")
	ScopeName = "github.com/GlancingMind/opentelemetry-collector-contrib/exporter/opencensusexporter"
)

const (
	TracesStability  = component.StabilityLevelBeta
	MetricsStability = component.StabilityLevelBeta
)
