// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("filestats")
	ScopeName = "github.com/GlancingMind/opentelemetry-collector-contrib/receiver/filestatsreceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
