// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("vcenter")
	ScopeName = "github.com/GlancingMind/opentelemetry-collector-contrib/receiver/vcenterreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
