// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("asapclient")
	ScopeName = "github.com/GlancingMind/opentelemetry-collector-contrib/extension/asapauthextension"
)

const (
	ExtensionStability = component.StabilityLevelBeta
)
