// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("sentry")
	ScopeName = "github.com/GlancingMind/opentelemetry-collector-contrib/exporter/sentryexporter"
)

const (
	TracesStability = component.StabilityLevelBeta
)
