// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("coralogix")
	ScopeName = "github.com/GlancingMind/opentelemetry-collector-contrib/processor/coralogixprocessor"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
