// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("alertmanager")
	ScopeName = "github.com/GlancingMind/opentelemetry-collector-contrib/exporter/alertmanagerexporter"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
